---
title: "ABCs data import"
author: "Dan Weinberger"
date: '2022-09-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(plotly)
#install.packages("waffle", repos = "https://cinc.rud.is") 
library(waffle)
library(reshape2)
source('./R/process_ecdc.R')
```


```{r}
#a1 <- read.csv('https://data.cdc.gov/api/views/en3s-hzsr/rows.csv?accessType=DOWNLOAD')

#saveRDS(a1,'./Data/ABCs_data_summary_2022_09_04.rds')

a1 <-readRDS('./Data/ABCs/ABCs_data_summary_2022_09_04.rds')
```

Based on ABCs Bact-Facts, projected 3250 IPD deaths nationally in 2019. In 2019 there were 810 deaths nationally recorded as J13 (pneumococcal pneumonia) or A40.3 (pneumococcal septicemia) or G00.1 (pneumococcal meningitis) from CDC WONDER (B95.3 was not on WONDER). With the line list data we get 923 with J13, A40.3, G00.1, B95.3. There were 537 Streptococcal sepsis (A40.8/A40.9)


ABCS genomic data are in: https://www.ncbi.nlm.nih.gov/bioproject/284954

```{r}
p1 <- a1 %>%
  filter(Topic =='Case Rates' & ViewBy=='Age' & Year>=1998) %>%
 ggplot( aes(x=Year, y=Value, col=ViewBy2)) +
  geom_line() +
  theme_classic() 

ggplotly(p1)
```

```{r}
p2 <- a1 %>%
  filter(Topic =='Death Rates' & ViewBy=='Age' & Year>=1998) %>%
 ggplot( aes(x=Year, y=Value, col=ViewBy2)) +
  geom_line() +
  theme_classic() 

ggplotly(p2)
```


```{r, fig.width=12, fig.height=4}
b2019 <- read.csv('./Data/ABCs/jiac058_suppl_supplementary_table_s2.csv') %>%
  group_by(State, sero, LT5) %>%
  summarize(N_cases=n()) %>%
  mutate(sero=as.factor(sero)) %>%
  ungroup() %>%
  group_by(State, LT5) %>%
  mutate(pct = N_cases/sum(N_cases)) %>%
  ungroup()
  
ggplotly(ggplot(b2019[b2019$LT5=='neg',], aes(fill=State, y=pct, x=sero)) + 
    geom_bar(position="dodge", stat="identity") 
) 
```
correlations
```{r}

adult.c <- b2019 %>%
  filter(LT5=='neg') %>%
  ungroup() %>%
  group_by(sero) %>%
  mutate(tot_N_cases=sum(N_cases)) %>%
  ungroup() %>%
  filter(tot_N_cases >= 10) %>%
 dcast(  State ~ sero, value.var='pct') %>%
  replace(is.na(.), 0)

cor(adult.c[,-1])
```



```{r}


  p3 <- ggplot(b2019[b2019$LT5=='neg',], aes(fill = sero, values = N_cases)) +
    geom_waffle(color='white', size = 0.25) +
  facet_wrap(~State) +
  theme_classic()
ggplotly(p3)
```


```{r}
ecdc <- process_ecdc()
```


